analytics.integration.enable=true
analytics.onpremise.enable=false
analytics.project={"id"\:3456253,"name"\:"Sample - HR Web App \#3456253","teamId"\:3435744,"status"\:null,"gitRepositories"\:null,"team"\:null,"organizationId"\:3484078,"autoIntegrate"\:false,"sampleProject"\:false,"accountId"\:null}
analytics.team={"id"\:3435744,"role"\:null,"name"\:null,"organization"\:null}
analytics.testcloud.integration.enable=true
analytics.testreport.autoupload.enable=true
